### ISSUE TITLE
How to convert an old application to Vert.x ? with mod-jersey / mod-cassandra 

### ISSUE THREAD

**Issue by thierryler** [englishtown/vertx-jersey#29]
Hello,

I'm rewriting an old application that uses CXF and Cassandra. There are 3 layers working with Spring (core) : Web (cxf), service (with business rules in Java) and DAO (Cassandra).

I'd like to replace all this with Vert.x, using vertx-jersey for the Web layer and vertx-cassandra for the DAO layer. 

Do you have recommandations / best practices ? Should I deployer verticles to replace each layer, for example ?

Thx,
Th.

**Comment by adrianluisgonzalez** [comment]
1. If you can tolerate a pre-release version of vert.x, use vert.x 3 (currently 3.0.0-milestone3).  The dependency management is so much simpler than the module system in vert.x 2.
2. Use something to help with the async nature of vert.x.  I'm clearly biased towards [vertx-when](/englishtown/vertx-when) which is promise based, but if you prefer RxJava that's the most commonly used option in the vert.x community.  The important thing is to have something to help avoid callback hell and run on the vert.x context.

I have seen Spring mentioned in the google group, I personally avoid it and use [HK2](/englishtown/vertx-hk2) or [Guice](/englishtown/vertx-guice) for DI.

The question of how many verticles you should have is a difficult one to answer.  There is a cost and complexity to serializing your objects and sending them over the event bus between verticles.  Depending on the size of the application and how modular you need/want to be, I would probably start with one verticle as you start working with vert.x.  For a small project, I use a project structure like this:

parent
    |_ core - contains POJO model objects, business logic, and interfaces
    |_ cassandra - contains implementations of data access persistors that are Cassandra specific.  Depends on core.
    |_ app - contains the main Verticle, Jersey resources, filters, etc.  This is the http REST layer and depends on core and cassandra.

Still keep each layer separated in different jars, but not necessarily separate Verticles per layer.  It's hard to generalize too much, but that's where I would start.

I tend to use the maven service factory to run the application, but you can also use the maven-shade plugin and run as a fat jar.

Hope this helps.

**Comment by adrianluisgonzalez** [comment]
Not sure if you have seen [vertx-cassandra](/englishtown/vertx-cassandra) now has vert.x helpers for the datastax mappers in the current SNAPSHOT build.  

https://github.com/englishtown/vertx-cassandra/blob/develop/vertx-cassandra-mapping/README.md

**Comment by thierryler** [comment]
Hello,

Thx for this great answer.

I'll start with Vert.x 3... Already in my pom ;-)

I am not sure to understand everything.The "core" maven module will contain my beans. The "cassandra" module will contain my DAO, and vertx-cassandra ? And the "app" module will contain the main class, and vertx-jersey.

By "main class" I mean a class with a "main()" method that deploys my verticles... I just copied what was proposed by vertx-jersey-webapp : https://github.com/NRaoV/vertx-jersey-webapp

```
public class MainVertx {

    private static final Vertx vertx = Vertx.vertx();

    public static void main(String[] args) {
        Context context = vertx.getOrCreateContext();
        JsonObject config = context.config();
        Properties props = CmdLineParser.getInstance().getCmdLineArgs(args);
        config.mergeIn(ConfigManager.loadConfig(props.getProperty(ServiceConstants.CONFIG_SOURCE)));
        //config.mergeIn(ConfigManager.loadConfig("my-ws-vertx/src/main/resources/config.json"));
        JsonObject jerseyConfig = config.getJsonObject(ServiceConstants.CONFIG_JERSEY);
        DeploymentOptions options = new DeploymentOptions();
        // options.setIsolationGroup("A");
        options.setConfig(jerseyConfig);

        // Specifying number of verticle instances, a rendre parametrable
        options.setInstances(16);

        // Jersey
        vertx.deployVerticle("java-hk2:" + JerseyVerticle.class.getCanonicalName(), options);

        // Service
        vertx.deployVerticle("com.mycorp.vertx.MonServiceVerticle");
    }
}
```

Just for now, I only have the web service part. I was thinking that the web service part, working with vertx-jersey, does not need so much CPU power. And the vertx-cassandra too... Am I wrong ? Therefore they could be on separated verticles...

```
@Path("/mywebservice")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class MyWebServiceVertx {

    @POST
    @Path("availability")
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    public AvaibilityResult getAvailability(AvailabilityCriteria availabilityCriteria) {
        AvaibilityResult result = foo(availabilityCriteria);
        return result;
    }
}
```

Here the class "MyWebServiceVertx" just receives the web service call, transforms the json to an object and then call the "foo()" method. In the "foo()" method, or instead of the "foo()" method call, I was thinking about calling other verticles with mod-rxvertx or vertx-when. But you suggest to perform the computation here directly?


```
public class MonServiceVerticle extends AbstractVerticle {

    @Override
    public void start() throws Exception {
        // ...
    }
}
```

By the way, do you have a full "pet shop" example, using both vert-jersey and vert-cassandra, somewhere?

Thx,
Th.

**Comment by adrianluisgonzalez** [comment]
The example from NRaoV is running as an embedded vert.x instance.  I would recommend running as a pure vert.x application using either a fat jar or the [vertx-maven-service-factory](https://github.com/vert-x3/vertx-maven-service-factory).  I personally use vertx-maven-service-factory for my applications.  My start script looks something like this:
```
vertx run service:com.englishtown.vertx.examples:vertx-example:1.0-SNAPSHOT -conf config.json -instances 4
```
If you run the vertx bash script without any arguments it will print the help.

The examples in vertx-jersey use fat jars with the maven-shade plugin.  See the [README.md](https://github.com/englishtown/vertx-jersey/tree/develop/examples).  This means you can run them like this:
```
java -jar target/{artifactId}-{version}-fat.jar -conf src/test/resources/config.json
```

I don't have a full "pet shop" example, all of these packages have grown from internal needs.  I'll try to put together an example demonstrating the full stack I typically use.

**Comment by thierryler** [comment]
Thx
