### ISSUE TITLE
vertx-jersey should be able to instantiated without JsonObject

### ISSUE THREAD

**Issue by testn** [englishtown/vertx-jersey#39]
Most of the configurations should be able to instantiated without relying on JsonObject from deployVerticle

**Comment by adrianluisgonzalez** [comment]
You can always inject your own implementation of `JerseyOptions` that has no dependency on the `JsonObject` from `deployVerticle()`.

Can you provide a little more detail about the issue you are running into?

**Comment by testn** [comment]
The problem is that GuiceJerseyBinder seems to inject JerseyOptions already so turning off is not easy. In addition to that, implementation JerseyOptions seems to be a kludgy at best because the interface it needs to implements is not quite well defined e.g.
- the listing of resources configuration is in the same location as other configurations that can be configured in vert.x itself (i.e. accept backlog, base uri, host, port, etc.)
- the options need to be configured at runtime via init() method makes it a bid odd to use it with Guice instead of being able to inject it cleanly via Guice injection.

**Comment by adrianluisgonzalez** [comment]
Fair points.

The init() methods are left over from the early days where the configuration was not available in the constructor.  Long overdue for a refactor.

I have changed `JerseyOptions` to split out vert.x `HttpServerOptions` into a separate interface `JerseyServerOptions` which is only injected into `DefaultJerseyServer`.

You can see the branch [here](https://github.com/englishtown/vertx-jersey/tree/feature/jersey-options-refactor).

Using just `JerseyHandler` and injecting your own implementation of `JerseyOptions` should now be trivial with `Modules.override()`.

Thoughts?
