### ISSUE TITLE
JerseyHandler should be able to be used with JerseyServer/JerseyVerticle

### ISSUE THREAD

**Issue by testn** [englishtown/vertx-jersey#40]
For example, I want to create a verticle to host static content and jersey REST endpoint at the same time. For that, I would wire JerseyHandler to vert.x web handler directly instead.

**Comment by adrianluisgonzalez** [comment]
I think there are two ways to achieve this:

1. Let `JerseyServer` create the vert.x `HttpServer` and provide a [setupHandler(Handler\<HttpServer\> handler)](https://github.com/englishtown/vertx-jersey/blob/develop/vertx-jersey/src/main/java/com/englishtown/vertx/jersey/JerseyServer.java#L57).  You can then wrap the Jersey handler and provide your own routes.

2. Create the HttpServer and routes in vert.x web as you normally would and provide the `JerseyHandler` for whatever route you want.  To initialize the `JerseyHandler` you would need to follow similar steps used by the `JerseyServer` [here](https://github.com/englishtown/vertx-jersey/blob/develop/vertx-jersey/src/main/java/com/englishtown/vertx/jersey/impl/DefaultJerseyServer.java#L88).

Do either of those options work for you?

**Comment by testn** [comment]
Yeah (2) 's  what I'm doing but the current initialization seems to be quite awkward with the injection of `DefaultVertxContainer` in order to create `JerseyHandler` and then later inject it via `init` method.

**Comment by adrianluisgonzalez** [comment]
See comment in #39
