### ISSUE TITLE
WhenJersey question

### ISSUE THREAD

**Issue by guedouarj** [englishtown/vertx-jersey#43]
Hello,

Maybe a stupid question, but is it mandatory to use promises (When) with Jersey ?

What is the benefit over RxJava for example ?

Thx

**Comment by adrianluisgonzalez** [comment]
Nope, absolutely not mandatory to use promises (although IMHO promises make more sense to help with async callbacks unless you are actually working with streams of data).

**Comment by guedouarj** [comment]
Ok ! Is it possible to complete your jersey-simple example using promises ( jerseyWhen ) for callbacks ?

By streams of data, you mean a framework like apache kafka ? Not about RxJava I suppose.

Thx!

**Comment by adrianluisgonzalez** [comment]
Sorry, I mispoke.  I really meant when you want to be reactive, then RxJava is a perfect candidate.  A classic example would be receiving continual updates for stock prices.

For when.java examples take a look at the examples and integration tests here:
https://github.com/englishtown/when.java
https://github.com/englishtown/vertx-when
https://github.com/englishtown/vertx-jersey/tree/develop/examples/when.java

**Comment by guedouarj** [comment]
So we can say that When.java is an alternative to RxJava ?

**Comment by adrianluisgonzalez** [comment]
Yes, for some scenarios they are alternatives.

You can search for comparisons between reactive vs promises for more details.

**Comment by guedouarj** [comment]
Thx Adrian for your precious answers,

I have a little question regarding a module: jdbc-client or rxJava

I saw that both can do async SQL commands like:

"INSERT INTO *....."
"SELECT FROM *.."

I don't understand then why its not possible to use JPA/Hibernate Named Queries for that ?
Its because JPA blocks threads  ?

There is no solution for that ?
I saw this but Im not sure if its stable enough: 

https://github.com/aesteve/vertx-hibernate-service


Thx !

**Comment by adrianluisgonzalez** [comment]
You'll need to ask the module owners, I don't know the details of jdb-client.  Or try the vert.x google group.
